-- 20260608000090_update_vendor_profiles.sql

ALTER TABLE public.vendors
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS location TEXT,
ADD COLUMN IF NOT EXISTS about TEXT,
ADD COLUMN IF NOT EXISTS features TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS packages JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS starting_price NUMERIC(10, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS rating NUMERIC(3, 1) DEFAULT 5.0,
ADD COLUMN IF NOT EXISTS reviews_count INTEGER DEFAULT 0;
